import { Product, TopupItem, StoreSettings, AccountItem, OfferItem, AffiliateProduct } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  bkash_number: '01859000000',
  nagad_number: '01859000000',
  rocket_number: '01859000000',
  usd_to_bdt_rate: 125,
  aliexpress_shipping_flat_bdt: 350,
  notice_text: '⚡ Instant Delivery! Pay via bKash / Nagad / Rocket. Free Fire & PUBG Top-Up completed in 5-15 mins!',
  whatsapp_number: '+8801859000000',
  help_phone: '01859000000',
  recharge_api_url: '',
  recharge_api_key: '',
  recharge_api_status: 'manual',
  recharge_api_provider: 'custom',
  custom_categories: [
    { id: 'digital', label: 'Digital Keys' },
    { id: 'physical', label: 'Physical Gadgets' },
    { id: 'gaming', label: 'Gaming Gift Cards' },
    { id: 'vpn', label: 'Premium VPN Accounts' }
  ],
  maintenance_mode: false,
  bkash_cashout_charge_percent: 1.85,
  stock_alert_limit: 5,
  enable_live_logs: true,
  events: [],
  active_event_popup_id: null,
  footer_title: 'Veloral Digital & Shop',
  footer_description: 'One-stop online portal for instant software license keys, smart gadgets, Free Fire & PUBG top-up, and AliExpress on-demand shopping in Bangladesh.',
  footer_copyright: '© 2026 Veloral Digital & Shop. All rights reserved.',
  footer_payment_methods: '✓ bKash Personal\n✓ Nagad Personal\n✓ Rocket Personal\n✓ Cash on Delivery',
  footer_help_text: 'Need assistance with an order? Contact our support line or chat on WhatsApp.',
};

export const INITIAL_PRODUCTS: Product[] = [
  // Digital Products
  {
    id: 'prod-win11-pro',
    product_code: 'VEL-WIN11',
    title: 'Windows 11 Pro Lifetime License Key',
    category: 'digital',
    price: 650,
    discount_price: 1200,
    image_url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80',
    description: '100% Genuine Retail Key for 1 PC. Lifetime activation with official Microsoft updates. Instant digital delivery on screen & SMS.',
    stock: 50,
    badge: 'Best Seller',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
    digital_payload: 'WIN11P-XXXXX-XXXXX-XXXXX-GENUINE',
    download_file_url: 'https://software-download.microsoft.com/download/pr/MediaCreationToolW11.exe',
    file_name: 'Windows_11_Pro_Official_Installer.exe',
    file_size: '9.6 MB',
  },
  {
    id: 'prod-canva-pro-1y',
    product_code: 'VEL-CANVA',
    title: 'Canva Pro 1 Year Subscription (Edu/Pro)',
    category: 'digital',
    price: 250,
    discount_price: 600,
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    description: 'Canva Pro access directly on your personal email. Access 100M+ premium assets, magic AI tools, background remover, and brand kits.',
    stock: 99,
    badge: 'Instant Invite',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
    digital_payload: 'https://canva.com/brand/join?invite_token=VELORAL_CANVA_ACCESS',
    download_file_url: 'https://canva.com/brand/join?invite_token=VELORAL_CANVA_ACCESS',
    file_name: 'Canva_Pro_VIP_Activation_Guide.pdf',
    file_size: '2.1 MB',
  },
  {
    id: 'prod-office-365',
    product_code: 'VEL-OFF365',
    title: 'Microsoft Office 365 Pro Plus (5 Devices, 1 Year)',
    category: 'digital',
    price: 490,
    discount_price: 999,
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80',
    description: 'Includes Word, Excel, PowerPoint, Outlook, OneNote, 1TB OneDrive cloud storage. Works on Windows, Mac, Android, and iOS.',
    stock: 35,
    badge: 'Official',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
    digital_payload: 'account@veloral365.onmicrosoft.com | TempPass123#',
    download_file_url: 'https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/O365HomePremRetail.img',
    file_name: 'Office_365_ProPlus_Setup_Guide.pdf',
    file_size: '3.4 MB',
  },
  {
    id: 'prod-kaspersky-total',
    product_code: 'VEL-KASP',
    title: 'Kaspersky Total Security Antivirus (1 Device, 1 Year)',
    category: 'digital',
    price: 450,
    discount_price: 850,
    image_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    description: 'Full protection against ransomware, viruses, phishing, and malware with safe online banking shield.',
    stock: 40,
    badge: 'Security',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
    digital_payload: 'KASP-XXXX-XXXX-XXXX-VALID',
    download_file_url: 'https://www.kaspersky.com/downloads/thank-you/total-security',
    file_name: 'Kaspersky_Total_Security_Installer.exe',
    file_size: '4.8 MB',
  },
  {
    id: 'prod-netflix-uhd',
    product_code: 'VEL-NETF',
    title: 'Netflix Premium 4K Ultra HD (1 Month Profile)',
    category: 'digital',
    price: 320,
    discount_price: 450,
    image_url: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=600&q=80',
    description: 'Private PIN-protected 4K UHD Profile. High-speed streaming guarantee, continuous 30 days playback on Mobile, TV, or PC.',
    stock: 20,
    badge: 'Popular',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
    digital_payload: 'netf_sub@veloral.top | Profile: PIN-5059',
    download_file_url: 'https://netflix.com',
    file_name: 'Netflix_4K_Profile_PIN_Access_Card.pdf',
    file_size: '1.2 MB',
  },

  // Physical Products
  {
    id: 'prod-tws-m10',
    product_code: 'VEL-M10',
    title: 'M10 TWS Wireless Bluetooth 5.3 Gaming Earbuds',
    category: 'physical',
    price: 480,
    discount_price: 850,
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    description: 'Deep heavy bass, LED digital power display, 2000mAh charging case with emergency powerbank function, IPX7 waterproof.',
    stock: 45,
    badge: 'Hot Deal',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
  },
  {
    id: 'prod-smartwatch-t800',
    product_code: 'VEL-T800',
    title: 'T800 Ultra Smartwatch Series 8 (1.99" HD Display)',
    category: 'physical',
    price: 890,
    discount_price: 1550,
    image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
    description: 'Bluetooth calling, heart rate monitor, multi-sports tracking, wireless charging with comfortable orange sports strap.',
    stock: 28,
    badge: 'Top Pick',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
  },
  {
    id: 'prod-fast-charger-65w',
    product_code: 'VEL-CHG65',
    title: 'GaN 65W Super Fast Charger 3-Port (Type-C + USB)',
    category: 'physical',
    price: 950,
    discount_price: 1400,
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    description: 'Supports PD 3.0 & QC 4.0 fast charging for laptops, iPhone, Samsung, Xiaomi. Compact travel size with surge protection.',
    stock: 32,
    badge: 'Fast Charge',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
  },
  {
    id: 'prod-rgb-mouse-gaming',
    product_code: 'VEL-RGBM',
    title: 'RGB 7-Button Optical Gaming Mouse (7200 DPI)',
    category: 'physical',
    price: 520,
    discount_price: 799,
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    description: 'Ergonomic shape, programmable macro buttons, dynamic breathing RGB lighting with braided anti-tangle USB cable.',
    stock: 19,
    badge: 'Gaming',
    is_flash_sale: true,
    is_hot_sale: true,
    is_for_you: true,
  }
];

export const INITIAL_TOPUPS: TopupItem[] = [
  // Free Fire
  {
    id: 'ff-115',
    game: 'freefire',
    name: 'Free Fire 115 Diamonds',
    amount_label: '115 💎',
    price: 85,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/3408/3408545.png',
  },
  {
    id: 'ff-240',
    game: 'freefire',
    name: 'Free Fire 240 Diamonds',
    amount_label: '240 💎',
    price: 170,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/3408/3408545.png',
  },
  {
    id: 'ff-610',
    game: 'freefire',
    name: 'Free Fire 610 Diamonds',
    amount_label: '610 💎',
    price: 420,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/3408/3408545.png',
  },
  {
    id: 'ff-weekly',
    game: 'freefire',
    name: 'Free Fire Weekly Membership',
    amount_label: 'Weekly Pass 🎫',
    price: 190,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/3408/3408545.png',
  },
  {
    id: 'ff-monthly',
    game: 'freefire',
    name: 'Free Fire Monthly Membership',
    amount_label: 'Monthly Pass 👑',
    price: 890,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/3408/3408545.png',
  },

  // PUBG Mobile
  {
    id: 'pubg-60',
    game: 'pubg',
    name: 'PUBG Mobile 60 UC',
    amount_label: '60 UC 🪙',
    price: 95,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/1068/1068778.png',
  },
  {
    id: 'pubg-325',
    game: 'pubg',
    name: 'PUBG Mobile 325 UC',
    amount_label: '325 UC 🪙',
    price: 460,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/1068/1068778.png',
  },
  {
    id: 'pubg-660',
    game: 'pubg',
    name: 'PUBG Mobile 660 UC (Royale Pass)',
    amount_label: '660 UC 🎖️',
    price: 890,
    icon_url: 'https://cdn-icons-png.flaticon.com/512/1068/1068778.png',
  },

  // Mobile Recharge
  {
    id: 'rec-50',
    game: 'mobile_recharge',
    name: 'Mobile Balance ৳50',
    amount_label: '৳50 Balance',
    price: 50,
  },
  {
    id: 'rec-100',
    game: 'mobile_recharge',
    name: 'Mobile Balance ৳100',
    amount_label: '৳100 Balance',
    price: 100,
  },
  {
    id: 'rec-200',
    game: 'mobile_recharge',
    name: 'Mobile Balance ৳200',
    amount_label: '৳200 Balance',
    price: 200,
  },
  {
    id: 'rec-500',
    game: 'mobile_recharge',
    name: 'Mobile Balance ৳500',
    amount_label: '৳500 Balance',
    price: 500,
  },
];

export const INITIAL_ACCOUNTS: AccountItem[] = [
  {
    id: 'acc-wa-1',
    product_code: 'ACC-WA-01',
    title: 'Aged WhatsApp Business Account (US/UK Number)',
    category: 'whatsapp',
    price: 350,
    discount_price: 600,
    image_url: 'https://cdn-icons-png.flaticon.com/512/733/733585.png',
    description: 'Aged & verified WhatsApp Business account with active status. Ready for marketing, customer support, or personal use. Instant credential delivery.',
    stock: 25,
    badge: 'Verified',
    account_credentials: 'Number: +1 (555) 382-9102\nPassword/2FA: SecurePin#9982\nRecovery Email: useracc992@gmail.com\nLogin Session Code: Provided on purchase',
  },
  {
    id: 'acc-tg-1',
    product_code: 'ACC-TG-01',
    title: 'Telegram Aged Account (With Channel Ready)',
    category: 'telegram',
    price: 280,
    discount_price: 500,
    image_url: 'https://cdn-icons-png.flaticon.com/512/2111/2111646.png',
    description: 'Aged Telegram account with clean history and 0 restriction. Includes TData session file & login instructions.',
    stock: 30,
    badge: 'Best Seller',
    account_credentials: 'Phone / Username: @tele_market_pro_99\nPassword: TGpass#77382\nTData Session File: Available for download upon order completion',
  },
  {
    id: 'acc-fb-1',
    product_code: 'ACC-FB-01',
    title: 'Facebook Aged Marketplace Account (2022 Verified)',
    category: 'facebook',
    price: 450,
    discount_price: 800,
    image_url: 'https://cdn-icons-png.flaticon.com/512/733/733547.png',
    description: 'Aged Facebook account created in 2022 with Marketplace enabled and phone verified. Ready for running ads or posting items.',
    stock: 15,
    badge: 'Hot Deal',
    account_credentials: 'Email/Phone: fb_user_market_881@outlook.com\nPassword: FBsecure#2026\n2FA Secret Key: JBSWY3DPEHPK3PXP\nCookie: Provided in details',
  },
  {
    id: 'acc-gm-1',
    product_code: 'ACC-GM-01',
    title: 'Aged Gmail Account (Phone Verified with Recovery)',
    category: 'gmail',
    price: 150,
    discount_price: 300,
    image_url: 'https://cdn-icons-png.flaticon.com/512/281/281764.png',
    description: 'High quality aged Gmail account, phone verified with recovery email included. Fully secure and ready for Google services.',
    stock: 50,
    badge: 'Instant',
    account_credentials: 'Email: verify.user.cloud99@gmail.com\nPassword: GmailPass#4491\nRecovery Email: backup.secure.mail@outlook.com',
  },
  {
    id: 'acc-nf-1',
    product_code: 'ACC-NF-01',
    title: 'Netflix Premium 4K UHD Ultra HD Private Profile',
    category: 'netflix',
    price: 220,
    discount_price: 400,
    image_url: 'https://cdn-icons-png.flaticon.com/512/2504/2504929.png',
    description: '1 Month Netflix 4K Ultra HD private profile with pin lock. Non-drop guarantee with replacement warranty.',
    stock: 40,
    badge: 'Warranty',
    account_credentials: 'Account Email: netflix.ultra.stream99@gmail.com\nPassword: NetPass#8821\nProfile Name: User 1 (PIN: 1234)',
  },
];

export const INITIAL_OFFERS: OfferItem[] = [
  {
    id: 'off-tg-10',
    title: 'Telegram Account Submit Task (১০ টাকা বোনাস)',
    platform: 'telegram',
    reward_amount: 10,
    description: 'আপনার সক্রিয় টেলিগ্রাম ইউজারনেম এবং অ্যাক্সেস পাসওয়ার্ড দিয়ে সাবমিট করুন। অ্যাডমিন ভেরিফাই করার পর সরাসরি আপনার ওয়ালেটে ১০ টাকা যোগ হয়ে যাবে!',
    instructions: '১. আপনার সঠিক টেলিগ্রাম ইউজারনেম দিন।\n২. প্রয়োজনীয় লগইন পাসওয়ার্ড বা ভেরিফিকেশন কোড দিন।\n৩. অ্যাডমিন যাচাই শেষে ব্যালেন্স জমা হবে।',
    icon_url: 'https://cdn-icons-png.flaticon.com/512/2111/2111646.png',
    active: true,
    requires_username: true,
    requires_password: true,
  },
  {
    id: 'off-wa-15',
    title: 'WhatsApp Micro Task (১৫ টাকা রিওয়ার্ড)',
    platform: 'whatsapp',
    reward_amount: 15,
    description: 'আপনার হোয়াটসঅ্যাপ নম্বর এবং ওটিপি/পিন সাবমিট করে ১৫ টাকা ওয়ালেট রিওয়ার্ড গ্রহণ করুন।',
    instructions: '১. সক্রিয় হোয়াটসঅ্যাপ নম্বর প্রদান করুন।\n২. পাসওয়ার্ড বা ওটিপি প্রদান করুন।\n৩. যাচাই শেষে রিওয়ার্ড যোগ হবে।',
    icon_url: 'https://cdn-icons-png.flaticon.com/512/733/733585.png',
    active: true,
    requires_username: true,
    requires_password: true,
  },
  {
    id: 'off-fb-20',
    title: 'Facebook Follow & Share Task (২০ টাকা বোনাস)',
    platform: 'facebook',
    reward_amount: 20,
    description: 'আমাদের ফেসবুক পেজ ফলো ও শেয়ার করে আপনার ফেসবুক প্রোফাইল লিংক বা ইউজারনেম এবং প্রমাণ সাবমিট করুন।',
    instructions: '১. ফেসবুক প্রোফাইল নাম বা ইউজারনেম দিন।\n২. স্ক্রিনশট বা প্রমাণের তথ্য দিন।\n৩. অনুমোদন হলে ২০ টাকা যোগ হবে।',
    icon_url: 'https://cdn-icons-png.flaticon.com/512/733/733547.png',
    active: true,
    requires_username: true,
    requires_password: false,
  },
  {
    id: 'off-gm-12',
    title: 'Gmail Verification Offer (১২ টাকা বোনাস)',
    platform: 'gmail',
    reward_amount: 12,
    description: 'ফ্রেশ জিমেইল অ্যাকাউন্ট সাবমিট করুন এবং তাৎক্ষণিক ১২ টাকা ওয়ালেটে উপার্জন করুন।',
    instructions: '১. জিমেইল অ্যাড্রেস লিখুন।\n২. পাসওয়ার্ড লিখুন।\n৩. অ্যাডমিন অ্যাপ্রুভ করার সাথে সাথে টাকা পাবেন।',
    icon_url: 'https://cdn-icons-png.flaticon.com/512/281/281764.png',
    active: true,
    requires_username: true,
    requires_password: true,
  },
];

export const INITIAL_AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  {
    id: 'aff-prod-1',
    name: 'Netflix Premium 1 Month Sub - Shared',
    slug: 'netflix-premium-1-month-shared-aff',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8fed85?auto=format&fit=crop&w=600&q=80',
    store_name: 'Daraz BD',
    category_id: 'digital',
    price: 150,
    old_price: 250,
    currency: 'BDT',
    short_description: 'Watch Netflix Premium 4K UHD on 1 screen. Shared premium profile.',
    description: 'Ultra HD streaming, 4K quality. Valid for 1 month. Access to 10,000+ films and series.',
    affiliate_url: 'https://www.daraz.com.bd/products/netflix-premium-shared-account-i347648342-s1709423851.html',
    tags: 'netflix,subscription,digital,ott',
    featured: true,
    status: 'active',
    display_order: 1,
    click_count: 145,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'aff-prod-2',
    name: 'Realme Buds Air 5 Wireless Earbuds - White',
    slug: 'realme-buds-air-5-earbuds-aff',
    image: 'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=600&q=80',
    store_name: 'Aliexpress',
    category_id: 'physical',
    price: 3200,
    old_price: 4500,
    currency: 'BDT',
    short_description: 'Active Noise Cancellation wireless gaming earbuds with super bass.',
    description: 'Active Noise Cancellation (ANC), 50dB Hybrid, Bluetooth 5.3, Super Low Latency gaming mode.',
    affiliate_url: 'https://www.aliexpress.com/item/1005005953048956.html',
    tags: 'realme,earbuds,gadgets,audio',
    featured: true,
    status: 'active',
    display_order: 2,
    click_count: 98,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

